### ISSUE TITLE
System volume and player volume disparity [Expires 2018-06-29]

### ISSUE THREAD

**Issue by a-johnston** [tiliado/nuvola-app-soundcloud#1]
Occurs in Soundcloud plugin version 1, Nuvola player version 3.0.0 on Debian Sid.

Appears that system volume is set to player volume, but player volume is never adjusted to match system volume. Upon a new track starting playback or a paused track resuming playback, system volume is set to player volume.

This does not occur in the other Nuvola-wrapped services I use, namely Google Play Music.

Resulted in music being initially played at max volume, which was fairly unpleasant.

Glanced through source but couldn't immediately see what was the issue. Not very familiar with codebase though.

**Comment by kixam** [comment]
hi @a-johnston,

Thank you for taking the time to write about this bug.

On my computer, SoundCloud/WebKit default volume set to 100% never was a problem, as I implicitly set my other applications volumes based on it (I realise that now...). This "chance" setting of course cannot be a solution to this issue.

AFAIK, Nuvola API does not give access to system volume from a plugin. I am not sure it would be an appropriate solution either anyway.

I think some internal SoundCloud script resets the "system" volume on its own accord to match this set in the web page. I know there is SoundCloud API that allows setting the volume by user script. I will look into it and try at least to save the volume as set from the SoundCloud volume control.

In any case, the solution I have in mind may not allow you to set the volume from any "system" interface in a permanent way, you might have to set it from Nuvola/SoundCloud interface.

**Comment by a-johnston** [comment]
It's of course difficult to read through minified JS but I didn't see anything going on with the volume upon playback resuming in the various scripts the button fires events on the soundcloud webpage. It would be interesting if it were able to, anyways. I'll definitely play around with it, but for now setting the volume manually saves my ears.

**Comment by a-johnston** [comment]
Also I'm not sure how I missed this earlier because I'm sure I tested it, but it seems like the system volume is set to max volume even when the player volume is lower. You may have already observed this, but I figured I'd post it in case it would help pinpoint the issue.

**Comment by kixam** [comment]
hello @a-johnston 

I observed the following:
* the player volume is saved between sessions (probably in a cookie or such) and thus does not need to be saved in Nuvola configuration files
* whenever the track being played changes (manual skip by pressing forward or backward button or picking a track, or automatic skip at the end of previous track) the system volume is reset to 100%, ignoring the player volume
* if the played track is paused then resumed (with "enough" delay between the two actions), the system volume is set according to the player volume

My understanding of SoundCloud's API is that it is supposed to work with their widget, that it itself is supposed to be embedded (using an `<iframe>`) within a page provided by a third party. Maybe I do not have to embed it really, but anyway, this would mean to start over, because so far the plugin is based on SoundCloud main, "normal" page, which I assume to be different from the widget page.

So, instead of overhauling my code or trying to reverse engineer SoundCloud's JS, I propose to provide an option that, when the user enables it, pauses-waits-plays the current track whenever the 2 following conditions are met:
* a track is currently being played
* the [artist, title] pair has changed

Before that, could you confirm the observations I made are valid in your environment too?

**Comment by a-johnston** [comment]
I haven't been able to recreate having the system volume set to the player volume. What is "enough" delay for your observation? This is having pulled + reinstalled the latest two updates. I also haven't observed the behavior when pausing/playing via the console on the soundcloud page.

**Comment by kixam** [comment]
I observed that in Firefox (out of Nuvola), the system volume is briefly set to 100% (during a few milliseconds) before it is reset to player volume. This does not happen in Nuvola, but pausing then playing the track does it, if you wait a dozen milliseconds or more (delay seems to depend on some refresh cycle, I am still investigating). There are still many things I do not understand about SoundCloud volume... I observe none of this in Deezer, either on Firefox or Nuvola, and Nuvola's Deezer plugin has no line of code involved in volume control AFAIK.

Just so we are clear, what I call "player volume" is the vertical volume bar at the bottom player bar on SoundCloud web page (this bar does not appear until you start playing a track). The "system volume" is, to me, the volume of WebKit application in pavucontrol (I am using PulseAudio).

Anyway, if you cannot reproduce this on your system, I have to look somewhere else.

**Comment by Eiamnacken** [comment]
I have the issue that everytime the songs changes, the volume goes up again to 100% also when i pause and play music again but systemwide. The volumecontrol within soundcloud does not change at all. Iam on
 KDE opensuse 42.1 Soundcloudplugin 1.1 Nuvolaplayer 3.0

**Comment by kixam** [comment]
I really do not understand this bug. It seems to me that it is related to or happening at WebKit backend, which is far from being accessible from a plugin. I can reproduce it on one of my computers and have been looking into it, but really I do not see a clean solution so far, just some JS tricks like a fast pause/play or such...

@fenryxo would you have any idea or advice as to where I could look at ?

**Comment by fenryxo** [comment]
Hello everybody. Thanks for your feedback. I'll probably get around to this issue as a part of the ticket "Check whether a web app volume slider is synchronized with a PulseAudio stream volume" tiliado/nuvolaplayer#139, currently tentatively scheduled for May 2016. For now, I recommend setting an appropriate volume directly in SoundCloud web interface.

**Comment by fenryxo** [comment]
Is the issue still present in [the latest flatpak builds](https://nuvola.tiliado.eu/app/soundcloud/)?
