### ISSUE TITLE
soundcould sign-in: can't sign in with Google auth

### ISSUE THREAD

**Issue by Thebeau** [tiliado/nuvola-app-soundcloud#3]
On Linux (gnome-ubuntu 14.04), while trying to sign in to soundcloud, clicking on the "Sign in with Google" button does nothing but render a cursor on it's left side.

SoundCloud ver 1.1
Nuvola 3.0.0 rev: 53b1d03843d1987c3510

Steps to repeat:
1. open the sound cloud app
2. click on "sign-in"
3. click on "Sign in with Google"
-> nothing happens

**Comment by SteVwonder** [comment]
Reproduced on:
Ubuntu 15.10
SoundCloud ver 1.1
Nuvola 3.0.0 rev: 53b1d03843d1987c3510

https://gist.github.com/SteVwonder/b2681a528e9a878abb93

**Comment by fenryxo** [comment]
Hello @Thebeau & @SteVwonder. The issue has just been fixed in the git *master* & *3.0.x* branches of [Nuvola Player](https://github.com/tiliado/nuvolaplayer). Thanks for your bug report.

The fix will be released in **Nuvola Player 3.0.1** (Nuvola Player 3.0 Stable Releases) and a next rebuild of **Nuvola Player 3.1.x** (Nuvola Player 3.1 Rolling Releases). To get informed when Nuvola Player 3.0.1 is released, follow Nuvola Player on [Facebook](https://www.facebook.com/nuvolaplayer), [Google+](https://plus.google.com/110794636546911932554) or [Twitter](https://twitter.com/NuvolaPlayer) or subscribe to the Nuvola Player Newsletter [weekly](http://eepurl.com/bLbm5H) or [monthly](http://eepurl.com/bLbtM1).

--

Jiří Janoušek, Nuvola Player Developer • *My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/).*
