### ISSUE TITLE
Is your network connection unstable or browser outdated?

### ISSUE THREAD

**Issue by bbuhler** [tiliado/nuvola-app-soundcloud#4]
![bildschirmfoto vom 2016-05-18 08 33 36](https://cloud.githubusercontent.com/assets/2802675/15349487/85a4bee4-1cd3-11e6-8c5a-4b968dfb62ec.png)

Nuvola Player Version: 3.0.2
SoundCloud Integration Version: 1.1

**Comment by kixam** [comment]
hello @bbuhler ,

Thank you for reporting this bug.

I assume you checked your internet connection is working fine.

I am running Nuvola with the same software versions and today (2016-05-18) everything works fine for me. But there is one more dependency to check.

Could you give your Web Engine version please ?

FYI, I am running with WebKitGTK 2.12.2. This would be updated through your Linux distribution. This library provides the underlying "web browser" that is used by Nuvola. It is part of GTK, not Nuvola.

**Comment by bbuhler** [comment]
Okay, I have WebKitGTK Version 2.8.5.
I'm using the Ubuntu 14.04 based elementary OS 0.3.

So I guess I have to wait until a new version gets published into my systems software sources.

**Comment by fenryxo** [comment]
> So I guess I have to wait until a new version gets published into my systems software sources.

That is unlikely to happen until the next release of your distribution. I've recently built [WebKitGTK 2.12.2 for all supported Ubuntu releases](https://launchpad.net/~nuvola-player-builders/+archive/ubuntu/webkit). Could you try out the package for Ubuntu 14.04 and report back? As a bonus, you will get all security updated that had been made since 2.8.5. Disclaimer: Due to insufficient funding, I haven't get a chance to test these packages yet. However, they are based on the official Debian packaging.

**Comment by fenryxo** [comment]
@kixam, it's necessary to show a warning about minimal required WebKitGTK version (see tiliado/nuvolaplayer#215). I'll take care of it though, ticket #5 created.

**Comment by bbuhler** [comment]
> Could you try out the package for Ubuntu 14.04 and report back?

Looks good.

**Comment by fenryxo** [comment]
Great :-) Closing in favour of #5.
